### ISSUE TITLE
Linking error VS2015

### ISSUE THREAD

**Issue by TheOrestes** [mlabbe/nativefiledialog#20]
When I tried linking it to my framework in VS2015, I got following linking error. I used VS2010 solution file, automatically upgraded to VS2015, compiled the static libs. 

```
unresolved external symbol __imp_strncat referenced in function "int __cdecl AppendExtensionToSpecBuf(char const *,char *,unsigned __int64)" (?AppendExtensionToSpecBuf@@YAHPEBDPEAD_K@Z)	GL_Framework	
C:\SourceControl\gl_framework\nfd_d.lib(nfd_win.obj)	1

unresolved external symbol __imp_strncpy referenced in function NFDi_UTF8_Strlen	GL_Framework	C:\SourceControl\gl_framework\nfd_d.lib(nfd_common.obj)	1
```
After changing options in "Code Generation>>Runtime Library" to /MTd instead of /MDd, my problem was solved. Maybe useful for someone in future.

**Comment by mlabbe** [comment]
In all Windows cases, you need to match the linked runtime library with the base executable's.  If switching it to /MTd worked, that's because you are linking against the static version of the library in your calling executable.

It is perfectly okay to make that change in the upgraded project file.

**Comment by TheOrestes** [comment]
Thanks for the reply & pretty awesome utility repo :)
