### ISSUE TITLE
Select Directory Support

### ISSUE THREAD

**Issue by emoon** [mlabbe/nativefiledialog#22]
Hi,

I wonder if there are any plans on supporting the ability to select a directory?

**Comment by mlabbe** [comment]
Hey,

Only reason it's not in there right now is because I didn't need it at the time I wrote the library.  I would accept an all-os pull request targeting the devel branch that adds NFD_PickFolder().  If you are entertaining this idea, I have added a small doc on submitting pull requests hree: https://github.com/mlabbe/nativefiledialog/blob/master/docs/submitting_pull_requests.md

Alternatively, I could add it under a support agreement (programming for hire is what I do for a living).

**Comment by emoon** [comment]
Alright. Thanks!

**Comment by paulsapps** [comment]
Any progress on this? I'm tempted to give it ago.

**Comment by emoon** [comment]
@paulsapps I have been been busy with other things so please go ahead :)

**Comment by paulsapps** [comment]
WIP here: https://github.com/paulsapps/nativefiledialog/tree/directory_support

win32 added, mac and linux todo

**Comment by mlabbe** [comment]
Great! I'll reopen the issue. :)

**Comment by mlabbe** [comment]
This is now checked in to the devel branch and, as of e2c28bbb, it's autobuilding on all platforms!

**Comment by emoon** [comment]
Sweet!

**Comment by mlabbe** [comment]
I forgot to mention: this was recently pushed to master.  Thanks again!
